resources:
  - name: go_test
    type: GitRepo
    configuration:
      path: vijayreddy1991/dummy
      branches:
        include: master
      gitProvider: my_integration #github
      tags:  # optional
        include: master
      buildOn:  # optional
         commit: true
         pullRequestCreate: true
         pullRequestClose: true
         releaseCreate: true
         tagCreate: true
      shallowDepth: 3 # optional       
      
pipelines:
  - name: localpipeline
    steps:
      - name: Bash1
        type: Bash
        configuration:   
          runtime:       
            type: image
            image:
              custom:
                name: vijaydocker1991/u18node
                tag: gotesting
                options: " "   
          inputResources:
            - name: go_test
        execution:
          onExecute:
            - node --version
            - echo "testing auto"
            
      - name: Bash2
        type: Bash
        configuration:   
          runtime:  
            type: image
            image:
              auto:
                language: node
                versions:
                  - 10.16.3                     
          inputSteps:
            - name: Bash1      
            
        execution:
          onExecute:
            - echo "success"
            
      - name: Bash3
        type: Bash
        configuration:   
          #runtime:  
          #  type: host  
          inputResources:
            - name: go_test              
          inputSteps:
            - name: Bash2   
            
        execution:
          onExecute:
            - echo "success"  
            - printenv
            - cd $res_go_test_resourcePath
            - sudo docker build -t shippabledocker/jfreq:latest .
