resources:
  - name: go_test
    type: GitRepo
    configuration:
      path: vijayreddy1991/artifactory-go-example
      branches:
        include: master
      gitProvider: my_integration #github
      
pipelines:
  - name: localpipeline
    steps:
      - name: BashVijaytest
        type: Bash
        configuration:   
          runtime:       
            type: image
            image:
              custom:
                name: vijaydocker1991/u18node
                tag: gotesting
                options: " "   
          inputResources:
            - name: go_test
        execution:
          onExecute:
            - printenv
            
#       - name: BashVijay1
#         type: Bash
#         configuration:   
#           runtime:  
#             type: image
#             image:
#               custom:
#                 name: vijaydocker1991/u18node
#                 tag: gotesting
#                 options: " "          
#         execution:
#           onExecute:
#             - printenv    
#             - ls
